name: Build and Run Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t my-nginx .

      - name: Run Docker Container
        run: |
          docker run -d -p 80:80 --name nginx-container my-nginx
          # This is a basic workflow to help you get started with Actions
      - name: Docker container inspect 
        run: |
          docker inspect nginx-container
